### ISSUE TITLE
Handle missing "performance"

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/prosthetic-hand#8] opened 2016-04-02 14:46 UTC
There is no performance in Safari 9.1.0, jake fails with: `Can't find variable: performance` in two tests.

**Comment by Invis1ble** [comment] 2016-10-02 04:47
The same issue in Opera 12.16 (I can't test it in newest Opera version):

> Undefined variable: performance

**Comment by jonkoops** [comment] 2023-06-09 12:30
Duplicate of #4

**Closed as not planned by jonkoops** 2023-06-09 12:30 UTC
